### ISSUE TITLE
[HomeFeed] 띄어쓰기 없는 긴 게시글

### ISSUE THREAD

**Issue by gyeongbaek** [17ANT/INATON#109]
### 🌱 무엇을 하실 건지 설명해주세요!
- 게시글 작성 시 띄어쓰기 없는 게시글 줄 바꿈이 되지 않는 오류

### 🌱 구현방법 및 예상 동작
- CSS 스타일링으로 수정

### 🌱 전달사항
- 현재 width 값이 변경되면서 Nav바가 위로 들리는 현상이 있습니다.

**Comment by gajua** [comment]
아아아ㅏ아ㅏ암ㄴㅇㄹ
